import fs from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';

const siteConfig = JSON.parse(
  fs.readFileSync(new URL('./config/site.json', import.meta.url), 'utf8')
);

const autogeneratedGroup = (label, directory) => ({
  label,
  items: [{ autogenerate: { directory } }]
});

export default defineConfig({
  site: siteConfig.site,
  base: siteConfig.base,
  integrations: [
    mermaid({
      autoTheme: true,
      enableLog: false,
      mermaidConfig: {
        securityLevel: 'strict',
        htmlLabels: false
      }
    }),
    starlight({
      title: 'DKKB',
      description: 'Daniel Kindl Knowledge Base for software engineering, architecture, AI, and LLM engineering.',
      customCss: ['./src/styles/starlight.css'],
      components: {
        MarkdownContent: './src/components/MarkdownContent.astro',
        PageTitle: './src/components/PageTitle.astro',
        TwoColumnContent: './src/components/TwoColumnContent.astro'
      },
      editLink: { baseUrl: 'https://github.com/daniel-kindl/dkkb/edit/main/' },
      lastUpdated: true,
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/daniel-kindl/dkkb' }
      ],
      sidebar: [
        {
          label: 'Foundations',
          items: [
            autogeneratedGroup('Principles', 'principles'),
            autogeneratedGroup('Architecture', 'architecture'),
            autogeneratedGroup('Decisions', 'decisions'),
            autogeneratedGroup('Patterns', 'patterns'),
            autogeneratedGroup('Anti-patterns', 'anti-patterns'),
            autogeneratedGroup('Problems', 'problems'),
            autogeneratedGroup('Practices', 'practices')
          ]
        },
        {
          label: 'Engineering',
          items: [
            autogeneratedGroup('Coding', 'coding'),
            autogeneratedGroup('Testing', 'testing'),
            autogeneratedGroup('Reliability', 'reliability'),
            autogeneratedGroup('Performance', 'performance'),
            autogeneratedGroup('Security', 'security'),
            autogeneratedGroup('Databases', 'databases'),
            autogeneratedGroup('API design', 'api-design')
          ]
        },
        {
          label: 'AI',
          items: [
            autogeneratedGroup('AI engineering', 'ai'),
            autogeneratedGroup('LLM engineering', 'llm')
          ]
        },
        {
          label: 'Personal',
          items: [autogeneratedGroup('Playbook', 'playbook')]
        },
        {
          label: 'Reference',
          items: [
            autogeneratedGroup('Glossary', 'glossary'),
            autogeneratedGroup('References', 'references')
          ]
        }
      ]
    })
  ]
});
